version: "3.9"

services:
    web:
        container_name: nginx
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./src:/var/www/html
            - ./config/nginx/app.conf:/etc/nginx/conf.d/default.conf
        links:
            - app
    app:
        container_name: app
        image: php:8-fpm
        build: ./config/php-fpm
        volumes:
            - ./src:/var/www/html
        links:
            - db
    db:
        container_name: mysql
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3307:3306
        env_file:
            - ./.env
        volumes:
            - ./dbdata:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        env_file:
            - ./.env
        ports:
            - 8082:80
        volumes:
            - /sessions
